"""empty message

Revision ID: 042c3ed979bd
Revises: 1319ead63936
Create Date: 2022-05-28 17:37:39.094801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042c3ed979bd'
down_revision = '1319ead63936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
